var canvas,ctx,ratio,numShapes=6,shps=[],loc,tloc,w,h,msg="straightdowntherabbithole",str1="down, down, down. would the fall never come to an end!",str2="down, down, down. there was nothing else to do, so alice soon began talking again.",bgCol,boxCol,boxCols=[],txtCol,boxShaCol,txtShaCol,speed,totalFrames;
function setup(){ratio=.625;var a=calcDimensionFromRatio(ratio);canvas=createCanvas(a.x,a.y);canvas.position((windowWidth-canvas.width)/2,(windowHeight-canvas.height)/2);noSmooth();w=width;h=height;colorMode(HSB,360,100,100,100);ctx=canvas.drawingContext;for(a=0;a<numShapes;a++)shps[a]=new Compound;textFont("moderno-fb");textStyle(ITALIC);textAlign(LEFT,TOP);noStroke();loc=createVector(w/2,h/2);tloc=loc.copy();vel=createVector();acc=createVector();bgCol=color(210,100,70);boxCol=color(0,0,100);boxCols[0]=
color(0,0,0);boxCols[1]=color(355,70,95);boxCols[2]=color(120,50,95);boxCols[3]=color(0,0,92);boxCols[4]=color(60,90,95);boxCols[5]=color(0,0,100);txtCol=color(0,0,0);boxShaCol=color(0,0,0,70);txtShaCol=color(0,0,0,30);totalFrames=360}
function draw(){background(bgCol);noStroke();fill(50,30,40);for(var a=0,c=0;c<h;c+=h/20){for(var b=0;b<w;b+=w/10)0==a%2?ellipse(b,c,20,20):ellipse(b+w/20,c,20,20);a++}speed=frameCount/totalFrames*TWO_PI;mouseIsPressed?(tloc.x=mouseX,tloc.y=mouseY):(tloc.x=w/2+constrain(map(rotationY,-30,30,-w/2,w/2),-w/2,w/2),tloc.y=h/2+constrain(map(rotationX,-30,30,-h/2,h/2),-h/2,h/2));loc.x=lerp(loc.x,tloc.x,.1);loc.y=lerp(loc.y,tloc.y,.1);ctx.shadowColor=txtShaCol;ctx.shadowBlur=.02*w;ctx.shadowOffsetX=.5*(w/
2-loc.x);ctx.shadowOffsetY=.5*(h/2-loc.y);push();translate(w/2,h/2);fill(txtCol);textCircle(.09*h,.09*h,.05*w);pop();a=w-.125*w;c=h-.125*w;for(b=numShapes-1;0<=b;b--){var d=lerp(w/2,loc.x,b/numShapes),e=lerp(h/2,loc.y,b/numShapes),f=shps[b];f.setContourRect(d,e,a-b*w*.13,c-b*h*.13);ctx.shadowColor=boxShaCol;ctx.shadowBlur=.1*w;ctx.shadowOffsetX=0;ctx.shadowOffsetY=0;fill(90+20*b,20*b,100-6*b);f.display();ctx.shadowColor=txtShaCol;ctx.shadowBlur=.02*w;ctx.shadowOffsetX=.35*(w/2-loc.x);ctx.shadowOffsetY=
.35*(h/2-loc.y);fill(txtCol);push();translate(w/2,h/2);fill(txtCol);1==b?textCircle(.36*h,.36*h,.16*w):3==b&&textCircle(.2*h,.2*h,.1*w);pop()}ctx.shadowColor="transparent";textSize(.033*w);textAlign(CENTER,TOP);textStyle(ITALIC);fill(50,20,70);a=.013*w;c=.013*w;push();translate(.5*w,c);text(str1,0,0);pop();push();translate(w-a,.5*h);rotate(PI/2);text(str2,0,0);pop();push();translate(.5*w,h-c);rotate(PI);text(str1,0,0);pop();push();translate(c,.5*h);rotate(-PI/2);text(str2,0,0);pop();stroke(50,20,
70);line(.15*w,.032*h,w-.15*w,.032*h);line(.952*w,.18*h,.952*w,h-.18*h);line(.15*w,h-.032*h,w-.15*w,h-.032*h);line(w-.952*w,.18*h,w-.952*w,h-.18*h);textStyle(NORMAL);textSize(.1*w);textAlign(CENTER,CENTER);fill(50,50,60);text("\u2666",.06*w,.06*h);text("\u2665",w-.06*w,h-.04*h);text("\u2663",w-.06*w,.06*h);text("\u2660",.06*w,h-.04*h)}
function textCircle(a,c,b){textAlign(CENTER,CENTER);textStyle(ITALIC);for(var d=0;d<msg.length;d++){var e=.7*cos(d*TWO_PI/msg.length-speed)*a,f=1.2*sin(d*TWO_PI/msg.length-speed)*c;push();translate(e,f);e=atan2(f,e);rotate(PI/2+e);textSize(b);text(msg[(d+floor(b))%msg.length],0,0);pop()}}function calcDimensionFromRatio(a){var c=windowWidth/windowHeight,b=createVector();c>a?(b.y=windowHeight,b.x=b.y*a):(b.x=windowWidth,b.y=1*b.x/a);return createVector(b.x,b.y)}
function windowResized(){var a=calcDimensionFromRatio(ratio);resizeCanvas(a.x,a.y);canvas.position((windowWidth-canvas.width)/2,(windowHeight-canvas.height)/2);w=width;h=height}var Compound=function(){this.ct=createVector();this.ctrH=this.ctrW=0};Compound.prototype.setContourRect=function(a,c,b,d){this.ct.x=a;this.ct.y=c;this.ctrW=b;this.ctrH=d};
Compound.prototype.display=function(){var a=.1*this.ctrW,c=.1*this.ctrW;beginShape();vertex(0,0);vertex(width,0);vertex(width,height);vertex(0,height);beginContour();vertex(this.ct.x-this.ctrW/2,this.ct.y);bezierVertex(this.ct.x-this.ctrW/2,this.ct.y+this.ctrH/2-c,this.ct.x-this.ctrW/2,this.ct.y+this.ctrH/2-c,this.ct.x-this.ctrW/2+a,this.ct.y+this.ctrH/2-c);bezierVertex(this.ct.x-this.ctrW/2+a,this.ct.y+this.ctrH/2,this.ct.x-this.ctrW/2+a,this.ct.y+this.ctrH/2,this.ct.x,this.ct.y+this.ctrH/2);bezierVertex(this.ct.x+
this.ctrW/2-a,this.ct.y+this.ctrH/2,this.ct.x+this.ctrW/2-a,this.ct.y+this.ctrH/2,this.ct.x+this.ctrW/2-a,this.ct.y+this.ctrH/2-c);bezierVertex(this.ct.x+this.ctrW/2,this.ct.y+this.ctrH/2-c,this.ct.x+this.ctrW/2,this.ct.y+this.ctrH/2-c,this.ct.x+this.ctrW/2,this.ct.y);bezierVertex(this.ct.x+this.ctrW/2,this.ct.y-this.ctrH/2+c,this.ct.x+this.ctrW/2,this.ct.y-this.ctrH/2+c,this.ct.x+this.ctrW/2-a,this.ct.y-this.ctrH/2+c);bezierVertex(this.ct.x+this.ctrW/2-a,this.ct.y-this.ctrH/2,this.ct.x+this.ctrW/
2-a,this.ct.y-this.ctrH/2,this.ct.x,this.ct.y-this.ctrH/2);bezierVertex(this.ct.x-this.ctrW/2+a,this.ct.y-this.ctrH/2,this.ct.x-this.ctrW/2+a,this.ct.y-this.ctrH/2,this.ct.x-this.ctrW/2+a,this.ct.y-this.ctrH/2+c);bezierVertex(this.ct.x-this.ctrW/2,this.ct.y-this.ctrH/2+c,this.ct.x-this.ctrW/2,this.ct.y-this.ctrH/2+c,this.ct.x-this.ctrW/2,this.ct.y);endContour();endShape()};