var animMode=0,or,ct,takeover=!1,totalFrames,tIndex=0,dTime=0,numTargets,tMode=[],tPos=[],tCol1=[],tCol2=[],tCol3=[],tCol4=[];function setup(){createCanvas(windowWidth,windowHeight);colorMode(HSB,360,100,100,100);noStroke();or=500/700;var a=color(0,0,100),d=color(220,90,90);color(340,65,80);tCol1.push(a);tCol2.push(d);tCol1.push(a);tCol2.push(d);reset();numTargets=tPos.length;totalFrames=240;ct=createVector(width/2,height/2)}var counter=0;
function draw(){color(58,70,90);var a=color(0,40,100),d=color(220,90,90);numTargets=tPos.length;totalFrames=240;var c=easingVector("easeInOutQuad",tPos[tIndex],tPos[(tIndex+1)%numTargets],dTime,totalFrames);animMode=tMode[tIndex];var b=map(constrain(mouseX,30,width-30),30,width-30,0,width),e=map(constrain(mouseY,30,height-30),30,height-30,0,height);takeover?(ct.x=lerp(ct.x,b,.1),ct.y=lerp(ct.y,e,.1)):(ct.x=lerp(ct.x,c.x,.1),ct.y=lerp(ct.y,c.y,.1));dTime++;0==frameCount%totalFrames&&(tIndex=(tIndex+
1)%numTargets,dTime=0,counter++);c=tCol1[tIndex%tCol1.length];b=tCol2[tIndex%tCol2.length];fill(a);rect(0,0,ct.x,ct.y);fill(b);30<ct.x&&30<ct.y&&syllable(15,15,ct.x-30,ct.y-30);2!=animMode?(fill(d),rect(ct.x,0,width-ct.x,ct.y),fill(c),ct.x<width-30&&30<ct.y&&syllable(ct.x+15,15,width-(ct.x+30),ct.y-30)):(fill(d),rect(ct.x,0,width-ct.x,height-ct.y),fill(c),ct.x<width-30&&ct.y<height-30&&syllable(ct.x+15,15,width-(ct.x+30),height-(ct.y+30)));fill(c);1!=animMode?(fill(d),rect(0,ct.y,ct.x,height-ct.y),
fill(c),30<ct.x&&ct.y<height-30&&syllable(15,ct.y+15,ct.x-30,height-(ct.y+30))):(fill(d),rect(0,ct.y,width-ct.x,height-ct.y),fill(c),ct.x<width-30&&ct.y<height-30&&syllable(15,ct.y+15,width-(ct.x+30),height-(ct.y+30)));0==animMode?(fill(a),rect(ct.x,ct.y,width-ct.x,height-ct.y),fill(b),ct.x<width-30&&ct.y<height-30&&syllable(ct.x+15,ct.y+15,width-(ct.x+30),height-(ct.y+30))):1==animMode?(fill(a),rect(width-ct.x,ct.y,ct.x,height-ct.y),fill(b),30<ct.x&&ct.y<height-30&&syllable(width-(ct.x-15),ct.y+
15,ct.x-30,height-(ct.y+30))):2==animMode&&(fill(a),rect(ct.x,height-ct.y,width-ct.x,ct.y),fill(b),ct.x<width-30&&30<ct.y&&syllable(ct.x+15,height-(ct.y-15),width-(ct.x+30),ct.y-30))}function reset(){tMode=[];tPos=[];tMode.push(2);tPos.push(createVector(0,0));tMode.push(2);tPos.push(createVector(0,height))}function windowResized(){resizeCanvas(windowWidth,windowHeight);reset()}function mousePressed(){takeover=!0}function mouseReleased(){takeover=!1}function keyPressed(){}
function syllable(a,d,c,b){var e=c/b;push();translate(a,d);if(0<=e&&e<=or){a=.6*c+c*map(constrain(e,0,or),0,or,-.105,0);d=.65*b;var f=0;var g=.68*b+b*map(constrain(e,0,or),0,or,-.025,0);var h=.6*c+c*map(constrain(e,0,or),0,or,-.105,0);var k=.32*b+b*map(constrain(e,0,or),0,or,.025,0);var l=.65*c;var m=0;c*=.35}else a=.6*c+c*constrain(map(e,or,6,0,.06),0,.06),d=.65*b+b*constrain(map(e,or,6,0,-.2),-.2,0),f=0,g=.68*b+b*constrain(map(e,or,6,0,-.1),-.1,0),h=.6*c+c*constrain(map(e,or,6,0,.06),0,.06),k=.32*
b+b*constrain(map(e,or,6,0,.1),0,.1),l=.65*c+c*constrain(map(e,or,6,0,.04),0,.04),m=0,c=.35*c+c*constrain(map(e,or,6,0,-.04),-.04,0);cho(0,0,a,d,e);jungH(f,g,h,k,e);jungV(l,m,c,b,e);pop()}
function cho(a,d,c,b,e){push();translate(a,d);beginShape();0<=e&&e<=or?(a=.33*c+c*map(constrain(e,0,or),0,or,.15,0),d=.33*b+b*map(constrain(e,0,or),0,or,.1,0)):(a=.33*c,d=.33*b+b*constrain(map(e,or,6,0,.2),0,.2));vertex(c/2,0);bezierVertex(c/2+a,0,c,b/2-d,c,b/2);bezierVertex(c,b/2+d,c/2+a,b,c/2,b);bezierVertex(c/2-a,b,0,b/2+d,0,b/2);bezierVertex(0,b/2-d,c/2-a,0,c/2,0);if(0<=e&&e<=or){a=.5*c;d=.85*b+b*map(constrain(e,0,or),0,or,.065,0);var f=.1*a+a*map(constrain(e,0,or),0,or,.1,0);e=.5*d+d*map(constrain(e,
0,or),0,or,0,0)}else a=.5*c+c*constrain(map(e,or,6,0,.35),0,.35),d=.85*b+b*constrain(map(e,or,6,0,-.3),-.3,0),f=.1*a+a*map(constrain(e,0,or),0,or,.3,0),e=.5*d+b*constrain(map(e,or,6,0,.06),0,.06);beginContour();vertex(c/2,(b-d)/2);bezierVertex(c/2-f,(b-d)/2,(c-a)/2,b/2-e,(c-a)/2,b/2);bezierVertex((c-a)/2,b/2+e,c/2-f,b-(b-d)/2,c/2,b-(b-d)/2);bezierVertex(c/2+f,b-(b-d)/2,c-(c-a)/2,b/2+e,c-(c-a)/2,b/2);bezierVertex(c-(c-a)/2,b/2-e,c/2+f,(b-d)/2,c/2,(b-d)/2);endContour();endShape();pop()}
function jungH(a,d,c,b,e){push();translate(a,d);0<=e&&e<=or?(a=.27*b+b*map(constrain(e,0,or),0,or,-.27,0),e=.22*c):(a=.27*b,e=.22*c+c*constrain(map(e,or,6,0,-.13),-.13,0));beginShape();vertex(0,b-a);vertex(c,b-a);vertex(c,b-.6*a);vertex(c-.2*c,b);vertex(0,b);vertex(0,b-a);endShape();beginShape();translate(.13*e,0);vertex(c/2-e/2,b-a+.1*a);vertex(c/2-e/2,.3*a);vertex(c/2-e,.15*a);vertex(c/2-e,0);vertex(c/2+e/2,0);vertex(c/2+e/2,b-a+.1*a);vertex(c/2-e/2,b-a+.1*a);endShape();pop()}
function jungV(a,d,c,b,e){push();translate(a,d);0<=e&&e<=or?(a=.1*b+b*map(constrain(e,0,or),0,or,-.08,0),d=.36*c):(a=.1*b,d=.36*c+c*constrain(map(e,or,6,0,-.26),-.26,0));beginShape();vertex(0,b);vertex(0,.3*a);vertex(.5*-d,.2*a);vertex(.5*-d,0);vertex(0,0);vertex(d,0);vertex(d,b-a);vertex(d-.5*d,b);vertex(0,b);endShape();push();translate(c-d,0);beginShape();vertex(0,b);vertex(0,.3*a);vertex(.5*-d,.2*a);vertex(.5*-d,0);vertex(0,0);vertex(d,0);vertex(d,b-a);vertex(d-.5*d,b);vertex(0,b);endShape();pop();
beginShape();0<=e&&e<=or?translate(0,.55*b+b*map(constrain(e,0,or),0,or,.1,0)):translate(0,.55*b+b*constrain(map(e,or,2,0,-.12),-.12,0));vertex(d-.1*d,0);vertex(c-d+.1*d,0);vertex(c-d+.1*d,a);vertex(d-.1*d,a);vertex(d-.1*d,0);endShape();pop()}
function easingVector(a,d,c,b,e){b=constrain(b/e,0,1);"linear"==a?b=linear(b):"easeInQuad"==a?b=easeInQuad(b):"easeOutQuad"==a?b=easeOutQuad(b):"easeInOutQuad"==a?b=easeInOutQuad(b):"easeInCubic"==a?b=easeInCubic(b):"easeOutCubic"==a?b=easeOutCubic(b):"easeInOutCubic"==a?b=easeInOutCubic(b):"easeInQuart"==a?b=easeInQuart(b):"easeOutQuart"==a?b=easeOutQuart(b):"easeInOutQuart"==a?b=easeInOutQuart(b):"easeInQuint"==a?b=easeInQuint(b):"easeOutQuint"==a?b=easeOutQuint(b):"easeInOutQuint"==a?b=easeInOutQuint(b):
"easeInOutExpo"==a&&(b=easeInOutExpo(b));return new createVector(d.x*(1-b)+c.x*b,d.y*(1-b)+c.y*b,d.z*(1-b)+c.z*b)}
function easing(a,d,c,b,e){b=constrain(b/e,0,1);"linear"==a?b=linear(b):"easeInQuad"==a?b=easeInQuad(b):"easeOutQuad"==a?b=easeOutQuad(b):"easeInOutQuad"==a?b=easeInOutQuad(b):"easeInCubic"==a?b=easeInCubic(b):"easeOutCubic"==a?b=easeOutCubic(b):"easeInOutCubic"==a?b=easeInOutCubic(b):"easeInQuart"==a?b=easeInQuart(b):"easeOutQuart"==a?b=easeOutQuart(b):"easeInOutQuart"==a?b=easeInOutQuart(b):"easeInQuint"==a?b=easeInQuint(b):"easeOutQuint"==a?b=easeOutQuint(b):"easeInOutQuint"==a?b=easeInOutQuint(b):
"easeInOutExpo"==a&&(b=easeInOutExpo(b));return d*(1-b)+c*b}function linear(a){return a}function easeInCubic(a){return pow(a,3)}function easeOutCubic(a){return 1-easeInCubic(1-a)}function easeInOutCubic(a){return.5>a?easeInCubic(2*a)/2:1-easeInCubic(2*(1-a))/2}function easeInQuad(a){return a*a}function easeOutQuad(a){return 1-easeInQuad(1-a)}function easeInOutQuad(a){return.5>a?2*a*a:-1+(4-2*a)*a}function easeInQuart(a){return a*a*a*a}function easeOutQuart(a){return 1- --a*a*a*a}
function easeInOutQuart(a){return.5>a?8*a*a*a*a:1-8*--a*a*a*a}function easeInQuint(a){return a*a*a*a*a}function easeOutQuint(a){return 1+--a*a*a*a*a}function easeInOutQuint(a){return.5>a?16*a*a*a*a*a:1+16*--a*a*a*a*a}function easeInOutExpo(a){return 0==a?0:1==a?1:.5>a?pow(2,20*a-10)/2:(2-pow(2,-20*a+10))/2};